# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_serveruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveruser',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
