# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_loginrecord_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveruser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
