# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=15),
            preserve_default=False,
        ),
    ]
