# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_server_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
